SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND TLNO IS NOT NULL AND DATE_OF_BIRTH like '%-03-%'
ORDER BY MEMBER_ID;